### ISSUE TITLE
usePersistedState: State not updated when key changes

### ISSUE THREAD

**Issue by BowlingX** [Akurganow/use-persisted-state#187]
Hi :),

thank you for this very useful library!
I found an issue when changing the `key` while using the hook `usePersistedState`.
It currently does not monitor changes to they `key`, so the state will not be fetched again from the storage, resulting in a stale state.

I can send a pull request for a change, although it can be fixed with a simple effect inside the hook (https://github.com/Akurganow/use-persisted-state/blob/master/src/create-persisted-state.ts#L20):

```ts
useEffect(() => {
      setState(initialOrPersistedValue)
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [ key, setState ])
```

I think it could also be fixed in https://github.com/Akurganow/use-persisted-state/blob/master/src/utils/use-storage-handler.ts#L68, as this monitors the key, but does currently not reset the state when it changes properly as I understand.

**Comment by Akurganow** [comment]
@BowlingX thanks you. This is a pretty weird case, but it makes sense, give me time to see how best to implement it.
