### ISSUE TITLE
is server side rendering SSR supported?

### ISSUE THREAD

**Issue by sgratzl** [Akurganow/use-persisted-state#196]
I'm currently using next.js to generate a website and it uses SSR to render the pages beforehand. However, as expected the localstorage doesn't match when hydrating the DOM. Moreover, it throws since `window` is not defined in the server setting

**Comment by Akurganow** [comment]
@sgratzl This is a client-only solution and I haven't planned SSR support
But if you have ideas how it could be implemented I ready to discuss

**Comment by sgratzl** [comment]
one approach is to have a construct like:
```
const [value, setValue] = useState(null);
useEffect(() => {
  if (window && window.localStorage) {
    setValue(...)
  }
});
```

However, this would enforce that everything is rendered twice. First time (server/hydrate) with no results and the second time with the current one

**Comment by Akurganow** [comment]
Check window existence is a solution only for localStorage and sessionStorage but the hook works with any storage that implements Storage interface and it's not always something that's in the window and as you said this would enforce everything rendering twice
It should be the Storage level solution and it seems like there is a solution to make the first rendering happen with an initial value, give me time to think about it
